version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATABASE_URL=mongodb://mongodb:27017/jobfit_db
    depends_on:
      - mongodb
    networks:
      - jobfit-network
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - jobfit-network
networks:
  jobfit-network:
    driver: bridge
volumes:
  mongodb_data: